CREATE TABLE T_MapLatam_Spanish (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indexation INT NOT NULL UNIQUE,
    sexo VARBINARY(512) NOT NULL,
    pais VARBINARY(512) NOT NULL,
    ciudad VARBINARY(512) NOT NULL,
    genotipo VARBINARY(512) NOT NULL,
    edad VARBINARY(64) NOT NULL
);