CREATE TABLE T_MapIndonesia_Ind (
    id INT PRIMARY KEY AUTO_INCREMENT,
    gender VARCHAR(255) NOT NULL,
    states VARCHAR(255) NOT NULL,
    genotype VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    groupAge VARCHAR(255) NOT NULL
);