CREATE TABLE T_MapIndonesia_Ind (
    id INT PRIMARY KEY AUTO_INCREMENT,
    gender VARBINARY(512) NOT NULL,
    states VARBINARY(512) NOT NULL,
    genotype VARBINARY(512) NOT NULL,
    age VARBINARY(64) NOT NULL,
    groupAge VARBINARY(512) NOT NULL
);