CREATE TABLE T_MapGreece_English (
    id INT PRIMARY KEY AUTO_INCREMENT,
    gender VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    genotype VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    groupAge VARCHAR(255) NOT NULL
);