CREATE TABLE T_MapPoland_Polish (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indexation VARCHAR(255) NOT NULL UNIQUE,
    gender VARCHAR(255) NOT NULL,
    genotype VARCHAR(255) NOT NULL,
    age VARBINARY(64) NOT NULL
);