CREATE TABLE T_MapGermany_Deutsch (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indexation VARCHAR(255) NOT NULL UNIQUE,
    gender VARCHAR(255) NOT NULL,
    genotype VARCHAR(255) NOT NULL,
    age INT NOT NULL
);