CREATE TABLE T_MapTurkey_Turkish (
    id INT PRIMARY KEY AUTO_INCREMENT,
    gender VARBINARY(512) NOT NULL,
    city VARBINARY(512) NOT NULL,
    genotype VARBINARY(512) NOT NULL,
    age VARBINARY(64) NOT NULL,
    groupAge VARBINARY(512) NOT NULL
);