CREATE TABLE T_FAST_Spain_MapSpain_Spanish (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indexation INT NOT NULL UNIQUE,
    sexo VARCHAR(255) NOT NULL,
    pais VARCHAR(255) NOT NULL,
    genotipo VARCHAR(255) NOT NULL,
    edad INT NOT NULL
);