CREATE TABLE T_MapBrazil_Portuguese (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indexation INT NOT NULL UNIQUE,
    gender VARBINARY(512) NOT NULL,
    genotype VARBINARY(512) NOT NULL,
    age VARBINARY(64) NOT NULL
);