CREATE TABLE T_MapGlobal (
    indexation INT PRIMARY KEY AUTO_INCREMENT,
    id INT NOT NULL UNIQUE,
    gender VARBINARY(512) NOT NULL,
    country VARBINARY(512) NOT NULL,
    genotype VARBINARY(512) NOT NULL,
    age VARBINARY(64) NOT NULL,
    groupAge VARBINARY(512) NOT NULL,
    linkDashboard VARBINARY(512)
);