CREATE TABLE T_MapFrance_English (
    indexation INT PRIMARY KEY AUTO_INCREMENT,
    id INT NOT NULL UNIQUE,
    annee VARBINARY(64) NOT NULL,
    code_Departement VARBINARY(512) NOT NULL,
    genoytype VARBINARY(512) NOT NULL,
    sexe VARBINARY(64) NOT NULL,
    difficultesSA VARBINARY(512) NOT NULL,
    age VARBINARY(64) NOT NULL,
    groupAge VARBINARY(512) NOT NULL
);