CREATE TABLE T_MapMalaysia_English (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indexation VARBINARY(512) NOT NULL UNIQUE,
    gender VARBINARY(512) NOT NULL,
    city VARBINARY(512) NOT NULL,
    states VARBINARY(512) NOT NULL,
    genotype VARBINARY(512) NOT NULL,
    age VARBINARY(64) NOT NULL,
    groupAge VARBINARY(512) NOT NULL
);